on: 
  workflow_dispatch:

jobs:
  example_job:
    runs-on: windows-latest
    steps:
      - name: Get tag or commit id
        id: get-commit-id
        shell: powershell
        run: result=("${{ github.sha }}").Substring(0,7) >> $GITHUB_ENV
      - name: Step 1 - Generate a value
        id: step1
        run: |
          echo "result=Hello, World!" >> $GITHUB_ENV
          echo "::set-output name=result::Hello, World!"

      - name: Step 2 - Use the value
        run: |
          echo "The result from get-commit-id is: ${{ steps.get-commit-id.outputs.result }}"
