on: 
  workflow_dispatch:

jobs:
  example_job:
    runs-on: windows-latest
    steps:
      - name: Get tag or commit id
        id: get-commit-id
        run: |
          $result = (("${{ github.sha }}").Substring(0,7))
          echo "Output_$result"
          echo "result=$result" >> $GITHUB_OUTPUT 

      - name: Step 2 - Use the value
        env:
          SUPER_SECRET: ${{ secrets.GIT_SECRET }}
        run: |
          echo "The result from get-commit-id is: Output [${{steps.get-commit-id.outputs.result}}]"
          echo "The result from get-commit-id is: $result"
          echo ${{ Secrets.GIT_SECRET }}
          echo "$env:SUPER_SECRET"
